# Generated by Django 2.1 on 2018-08-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='测试执行人', max_length=150, null=True)),
                ('version_num', models.PositiveIntegerField(help_text='版本号', null=True)),
                ('anr_num', models.IntegerField(blank=True, help_text='ANR异常数')),
                ('crash_num', models.IntegerField(blank=True, help_text='crash异常数')),
                ('exception_num', models.IntegerField(blank=True, help_text='exception异常数')),
                ('monkey_is_finish', models.BooleanField(default=False, help_text='是否正常结束')),
                ('bug_num', models.IntegerField(blank=True, help_text='bug数量')),
                ('remark', models.CharField(help_text='备注', max_length=30)),
            ],
        ),
    ]
