# Generated by Django 2.1 on 2018-09-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='result',
            fields=[
                ('数据主键id', models.IntegerField(primary_key=True, serialize=False)),
                ('项目名称', models.CharField(default='xiaob', max_length=20)),
                ('用例ID', models.CharField(max_length=10)),
                ('接口名称', models.CharField(default='获取订单列表接口', max_length=30)),
                ('case_description', models.CharField(max_length=300)),
                ('req_method', models.CharField(max_length=6)),
                ('req_url', models.CharField(max_length=100)),
                ('req_parameter', models.CharField(max_length=100)),
                ('checkpoint', models.CharField(max_length=100)),
                ('request_message', models.CharField(max_length=500)),
                ('response_message', models.CharField(max_length=500)),
                ('people', models.CharField(max_length=10)),
                ('test_res', models.CharField(max_length=10)),
                ('remarks', models.CharField(max_length=50)),
                ('times', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
