# Generated by Django 2.1 on 2018-09-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song02app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='times',
        ),
        migrations.AddField(
            model_name='result',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
